Mudar a qtd total de itens no DANFE da NFCe de somatório para contagem
ZeusAutomacao/DFe.NET pull request #1126
Opened 2020-06-10 13:46 UTC by gui-abrantes

Apenas mudei no .frx o campo de SUM para COUNT

2020-06-17 22:57 UTC, marcosgerene commented
Por favor, faça os ajustes e reabra outro PR.

2020-06-17 22:57 UTC, closed without merging

2020-06-17 22:57 UTC, marcosgerene requested changes

2020-06-17 22:57 UTC, marcosgerene commented on NFe.Danfe.Fast/NFCe/NFCe.frx
> +            <Column Name="tpNF" DataType="null"/>
Bem estranho para mim esse monte de alterações nos atributos... tem algo a ver com a versão do FR?

Se possível mande um PR alterando somente o que você precisa alterar SUM -> Count

2020-06-18 11:45 UTC, gui-abrantes commented on NFe.Danfe.Fast/NFCe/NFCe.frx
> +            <Column Name="tpNF" DataType="null"/>
Oi @marcosgerene , bom dia! Pois é, percebi isso mesmo quando fiz o PR, mas eu mudei somente no atributo TotaType na janela de propriedades. Conforme a imagem a seguir:

![image](https://user-images.githubusercontent.com/19655107/85016231-b4a52800-b13f-11ea-9ecb-3130f58088e4.png)

O designer que tenho aqui é um Demo:
![image](https://user-images.githubusercontent.com/19655107/85016287-d6061400-b13f-11ea-8670-d1fe7b445e19.png)

Ah não ser se eu editar na mão o frx e mudar. Mas será que não é perigoso corromper?

Como eu necessitava de uma certa urgência , eu mudei e já coloquei em produção e tá funcionando normal, sem nenhum erro.