[-] Corrigindo tipo dos campos pesoL, pesoB e cStat
ZeusAutomacao/DFe.NET pull request #1189
Opened 2020-10-28 21:06 UTC by marcosgerene

https://github.com/ZeusAutomacao/DFe.NET/issues/1187

2020-10-29 17:00 UTC, rrpinajr requested changes

2020-10-29 17:00 UTC, rrpinajr commented on Shared.NFe.Classes/Informacoes/Detalhe/ProdEspecifico/veicProd.cs
> +        public decimal pesoB { get; set; }
Este também precisar ser tipo string.
```suggestion
        public string pesoB { get; set; }
```

2020-10-29 18:35 UTC, marcosgerene commented on Shared.NFe.Classes/Informacoes/Detalhe/ProdEspecifico/veicProd.cs
> +        public decimal pesoB { get; set; }
Feito

2020-10-30 11:39 UTC, rafjsouza approved these changes

2020-10-30 13:59 UTC, rrpinajr approved these changes

2020-10-30 16:41 UTC, merged