Adicionados campos de retenção na Danfe
ZeusAutomacao/DFe.NET pull request #1257
Opened 2021-05-27 23:31 UTC by henrique25teles

A danfe imprimia apenas com o ISSQN como descrito na imagem
![image](https://user-images.githubusercontent.com/54913843/119908858-edda4080-bf29-11eb-84f6-6bf7d3511620.png)

Foi alterado para mostrar os dados de retenção na danfe como segue a imagem
![image](https://user-images.githubusercontent.com/54913843/119908946-1d894880-bf2a-11eb-82ce-29e1ad4c7f74.png)

Para utilizar essa opção, deve-se preencher na configuração do Danfe se exibe essas informações
![image](https://user-images.githubusercontent.com/54913843/119909030-51646e00-bf2a-11eb-951a-5d6b01d97edc.png)

![image](https://user-images.githubusercontent.com/54913843/119909124-84a6fd00-bf2a-11eb-97c5-40bd6bae7fff.png)

2021-06-04 00:24 UTC, danilobreda commented
Teve muitas alterações no .frx que não são exatamente para essa questão... como altura dos elementos etc, quanto mais alteração no frx mais dificil é a migração para os programadores finais, deve ter o mínimo possível disso.

Foi retirado todos os datatypes, não sei se isso é algo ok, é uma grande mudança e que pode causar problemas dependendo do cliente. Não tem essa necessidade.
![image](https://user-images.githubusercontent.com/14843499/120727741-b4697e00-c4b1-11eb-88e8-314463081da5.png)

Picture foi retirado o **Image = ""**, o que causa problemas em alguns casos no .Net 5 e outras versoes do openfastreport.

2021-06-04 20:50 UTC, danilobreda requested changes
Teve muitas alterações no .frx que não são exatamente para essa questão... como altura dos elementos etc, quanto mais alteração no frx mais dificil é a migração para os programadores finais, deve ter o mínimo possível disso.

Foi retirado todos os datatypes, não sei se isso é algo ok, é uma grande mudança e que pode causar problemas dependendo do cliente. Não tem essa necessidade.

Picture foi retirado o Image = "", o que causa problemas em alguns casos no .Net 5 e outras versoes do openfastreport.

2021-06-08 18:02 UTC, henrique25teles commented
@danilobreda Vou conferir o que aconteceu.
Eu não mechi nos datatypes, eu só baixei o programa do fastreport e ele fez sozinho essas mudanças e funcionou tranquilo pra mim.

Eu reparei que a versão do fastreport da versão anterior é de 2017, dificilmente eu conseguirei achar isso pra baixar para manter a compatibilidade 100%.

2021-06-09 18:09 UTC, danilobreda commented
vou copiar em um branch separado e arrumar a questão do fastreport que levantei.

2021-06-14 00:17 UTC, merged

2021-06-14 00:18 UTC, danilobreda commented
Vou fazer as alterações na branch que fiz o pullrequest e vou jogar posteriormente para o master. Obrigado pelo contribuição @henrique25teles  👍