Implementa DANFE HTML
ZeusAutomacao/DFe.NET pull request #1422
Opened 2023-06-08 11:05 UTC by DSBRBrasil

Segue para analise implementacao danfe em HTML modelo 55 sem nenhuma dependencia de software externo

2023-06-08 17:19 UTC, marcosgerene commented on CTe.AppTeste/App.config
Aqui estamos falando o AppTest, então não é necessariamente um problema, mas esse downgrade, na minha opinião não deveria estar nesse PR.

Vou chamar esse caso de 001.

2023-06-08 17:25 UTC, marcosgerene requested changes
Iniciei a revisão mas parei porque são muitos arquivos alterados sem necessidade.

Seria possível (sei que é um commit grande) isolar somente a adição, ou seja, remover desse PR o que diz respeito a outros projetos como o downgrade da versão do .NET nos App.Teste?

Obrigado pela contribuição, te garanto que vai ser muito útil para a comunidade!

2023-06-08 17:25 UTC, marcosgerene commented on CTe.AppTeste/CTe.AppTeste.csproj
001

2023-06-08 17:25 UTC, marcosgerene commented on CTe.AppTeste/Properties/Resources.Designer.cs
Esse objeto não deveria fazer parte desse PR.

Vou chamar de 002.

2023-06-08 17:25 UTC, marcosgerene commented on CTe.AppTeste/Properties/Settings.Designer.cs
002

2023-06-08 17:25 UTC, marcosgerene commented on CTe.Dacte.AppTeste/App.config
001

2023-06-08 17:25 UTC, marcosgerene commented on CTe.Dacte.AppTeste/CTe.Dacte.AppTeste.csproj
001

2023-06-08 17:25 UTC, marcosgerene commented on CTe.Dacte.AppTeste/Properties/Resources.Designer.cs
002

2023-06-08 17:25 UTC, marcosgerene commented on CTe.Dacte.AppTeste/Properties/Settings.Designer.cs
002

2023-06-08 17:25 UTC, marcosgerene commented on NFe.Danfe.AppTeste.Fast/app.config
001

2023-06-08 17:25 UTC, marcosgerene commented on NFe.Danfe.AppTeste.Fast/Properties/Settings.Designer.cs
002

2023-06-08 17:25 UTC, marcosgerene commented on NFe.Danfe.AppTeste.Fast/Properties/Resources.Designer.cs
002

2023-06-08 17:25 UTC, marcosgerene commented on NFe.AppTeste/app.config
001

2023-06-08 17:25 UTC, marcosgerene commented on NFe.AppTeste/Properties/Resources.Designer.cs
002

2023-06-08 17:25 UTC, marcosgerene commented on NFe.AppTeste/NFe.AppTeste.csproj
001

2023-06-08 22:37 UTC, DSBRBrasil commented on CTe.Dacte.AppTeste/Properties/Resources.Designer.cs
Não alterei arquivos existentes, foi apenas o projeto NFe.Danfe.Nativo2.
Fiz o fork, baixei o projeto e pronto.
Podem criar um branch e orientar ?

2023-06-10 11:44 UTC, robertorp commented
Alterou a versão dos projetos de testes apenas hehe , não ta dificil de mudar , vou olhar também seu projeto , o que você cirou foi o nativo2 para o html né ?

2023-06-10 20:11 UTC, DSBRBrasil commented
> Alterou a versão dos projetos de testes apenas hehe , não ta dificil de mudar , vou olhar também seu projeto , o que você cirou foi o nativo2 para o html né ?
@robertorp  Me lembrei que eu ja tinha o fork desse projeto há anos, e acredito que uma alteração antiga pode ter ido nesse pr, então pode descartar qualquer alteração em outros projetos. O único que deve ser foco de analise é o  **NFe.Danfe.Nativo2** 
Como funciona?

1. Para nao quebrar o layout a pagina inicial comporta: 
1.1  - 7 linhas se no pior caso houver mais de 800 caracteres entre os 7 primeiros registros de produtos, oque significa que há descrições com 120 caracteres permitidos em xProd
1.2  - 12 linhas se no melhor caso houver até 800 caracteres entre as 12 primeiras linhas do xml

2. Para nao qebrar o layout das paginas subsequentes à primeira:
2.1  - 24 linhas se no pior caso  houver uma contagem de mais de 3000 caracteres nas 24 primeiras linhas
2.2  - 50 linhas de no melhor caso houver uma contagem de até 3000 caracteres nas 50 primeiras linhas

Resumo: Após vários testes o layout se comportou muito bem, forcei mais de 100 itens (produtos) oscilando entre 20 a 120 caracteres. Quando em produção a maior parte das danfes continham de 1 a 3 itens e poucas no máximo com 19 itens

![image](https://github.com/ZeusAutomacao/DFe.NET/assets/7658282/208b8169-4bf7-45dd-85ea-261b147232b2)
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/7658282/5b90b2d5-8d3c-4d72-a21f-01087c741e45)
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/7658282/bba74ef4-be93-455e-9e1a-aa45b612714d)
Peço ajuda dos analistas para melhorem o codigo fonte

2023-06-10 20:18 UTC, DSBRBrasil commented on NFe.Danfe.AppTeste.Fast/Properties/Settings.Designer.cs
Descarte qualquer alteração de arquivo ! apenas foque no projeto NFe.Danfe.Nativo2

2023-06-13 20:44 UTC, DSBRBrasil commented
Pessoal,
Segue correção no CSS das imagens marca d'agua para que ao usar algum componente de conversao em PDF a imagem fique posicionada corretamente: ( a unidade mm foi convertida para polegadas e retirado o display: block)
O componente conversor para pdf é o  itext7.pdfhtml utilizado por mim é o 
`  
<style>
.nfeArea .imgCanceled {
    position: absolute;
    top: 2.95in;
    left: 1.18in;
    z-index: 3;
    opacity: 0.8; 
  }

  .nfeArea.invoiceCanceled .imgCanceled {
     /*display: block; (RETIRAR ESSE ESTILO)*/
  }

  .nfeArea .imgNull {
    position: absolute;
    top: 2.95in;
    left:0.79in;
    z-index: 3;
    opacity: 0.8; 
  }

  .nfeArea.invoiceNull .imgNull {
    /*display: block; (RETIRAR ESSE ESTILO)*/
  }

  .nfeArea.invoiceCancelNull .imgCanceled {
    top: 3.93in;
    left: 1.37in; 
  }

  .nfeArea.imgNull {
    top: 2.55in;
    left:0.59in; 
  }
</style>

`
Código fonte do conversor
![image](https://github.com/ZeusAutomacao/DFe.NET/assets/7658282/92e1b07d-2e04-4061-b618-386bdd4516c5)

2023-06-13 23:28 UTC, robertorp commented
@DSBRBrasil  olha esse branch que fiz pegando teu pull as partes que realmente importam e alterando somente onde necessário, você se importa de min fazer merge desse pull que fiz ? Digo isso porque por algum motivo o seu branch alterou muita coisa do Zeus , digo os projetos dele 
https://github.com/ZeusAutomacao/DFe.NET/tree/ra/feat-danfe-html-merge

2023-06-14 11:19 UTC, DSBRBrasil commented
> @DSBRBrasil olha esse branch que fiz pegando teu pull as partes que realmente importam e alterando somente onde necessário, você se importa de min fazer merge desse pull que fiz ? Digo isso porque por algum motivo o seu branch alterou muita coisa do Zeus , digo os projetos dele https://github.com/ZeusAutomacao/DFe.NET/tree/ra/feat-danfe-html-merge

Opa !!! Pode fazer oque for necessário. Eu errei ao pegar um fork meu que estava alterado e mandar o PR ( eu tinha esquecido que havia alterado para construção de uma outra solução com base no Zeus).
Assim que vc terminar, me avisa para que eu, a partir dessa nova branch correta criada por você, realize um ajuste no layout necessário quando for usar um componente de conversao para PDF (a marca d'agua nao estava sendo exibida ao converter para PDF usando o iTExtPDF

2023-06-14 13:17 UTC, robertorp commented
@DSBRBrasil  já está no master =) tem até app teste , obrigado , isso é muito bom esse danfe

2023-06-14 13:18 UTC, closed without merging