Integrar ajustes para MDFe no repositório original da biblioteca DFe.NET
ZeusAutomacao/DFe.NET pull request #1519
Opened 2024-05-28 18:37 UTC by andrebts

A biblioteca DFe.NET em seu módulo MDFe utiliza um conjunto de configurações estáticas que funcionam para aplicações com o contexto de apenas uma empresa. Entretanto, existe a necessidade em algumas aplicações de funcionar em um contexto multi-empresa.

A algum tempo atrás esses e outros ajustes foram feitos na [branch NET_Standard](https://github.com/andrebts/DFe.NET/tree/NET_Standard) de um fork pessoal. Entretanto, as mudanças que serão introduzidas pela nota técnica 2024.001 e futuras notas técnicas demandarão novas implementações. Então faz-se imperativo a unificação das modificações introduzidas na branch NET_Standard para a master do repositório original.

A alteração mais crucial foi a que ajustou a biblioteca para informar as configurações como instância e não estáticas (static) como eram. Como essas alterações nunca foram integradas ao repositório original, é esse comportamento foi reimplementado e a partir desse PR será integrado a branch master do repositório oficial.

2024-06-17 20:41 UTC, eldermatheus commented on MDFe.Classes/Informacoes/MDFeInfRespTec.cs
> +        public bool idCSRTSpecified
Acredito que essa variável deveria começar com letra maiúscula

2024-06-17 20:42 UTC, eldermatheus commented on MDFe.Damdfe.Fast/DamdfeFrMDFe.cs
> +
Remover essa linha sem necessidade

2024-06-17 21:18 UTC, AgnaldoSilva0 requested changes

2024-06-17 21:18 UTC, AgnaldoSilva0 commented on MDFe.Classes/Extensoes/ExtMDFe.cs
> +            if (MDFeConfiguracao.Instancia.NaoSalvarXml()) return;
Em alguns outros métodos, a instância é verificada usando a configuração recebida por parâmetro. Caso esta seja nula, é então utilizada a instância geral estática. Entretanto, neste método específico, a instância geral está sendo utilizada diretamente, independentemente de ter sido fornecida uma por parâmetro. Assim, é necessário ajustá-lo para dar prioridade à configuração recebida.

2024-06-17 21:18 UTC, AgnaldoSilva0 commented on MDFe.Damdfe.OpenFast/DamdfeFrMDFe.cs
> +       public void Configurar(ConfiguracaoDamdfe config)
Dê um espaço para o lado nessa linha, note que está desalinhada.

2024-06-18 11:42 UTC, AgnaldoSilva0 commented on MDFe.Servicos/ConsultaNaoEncerradosMDFe/ServicoMDFeConsultaNaoEncerrados.cs
>              var retorno = MDFeRetConsMDFeNao.LoadXmlString(retornoXml.OuterXml, consMDFeNaoEnc);
Na chamada de método abaixo `retorno.SalvarXmlEmDisco(cnpjCpf);`, ele também recebe a configuração como parâmetro. Você acha ideal usar a configuração nesse método, como foi feito nos outros acima?

Ficaria assim: `retorno.SalvarXmlEmDisco(cnpjCpf, cfgMdfe);`

2024-06-18 12:09 UTC, AgnaldoSilva0 commented on MDFe.Servicos/ConsultaProtocoloMDFe/ServicoMDFeConsultaProtocolo.cs
>              var retorno = MDFeRetConsSitMDFe.LoadXml(retornoXml.OuterXml, consSitMdfe);
Aqui também é o mesmo caso do comentário anterior, a chamada na linha 53 também pode receber a configuração como parâmetro.

Ficaria assim: `retorno.SalvarXmlEmDisco(chave, cfgMdfe);` (Linha 53)

2024-06-18 12:23 UTC, AgnaldoSilva0 commented on MDFe.Servicos/EventosMDFe/EventoPagamentoOperacao.cs
>  using MDFe.Classes.Informacoes.Evento.CorpoEvento;
`usign` sem uso.

2024-06-18 14:27 UTC, AgnaldoSilva0 commented on MDFe.Utils/Configuracoes/MDFeConfiguracao.cs
>  using VersaoServico = MDFe.Utils.Flags.VersaoServico;
`using's` sem uso:

```
using DFe.Classes.Entidades;
using DFe.Classes.Flags;
using VersaoServico = MDFe.Utils.Flags.VersaoServico;
```

2024-06-18 14:47 UTC, AgnaldoSilva0 commented on MDFe.Utils/Configuracoes/MDFeConfiguracao.cs
>          public void Dispose()
Não faz parte do código modificado, mas como essa classe sofreu alterações significativas e seguindo o princípio do escoteiro, poderia verificar o seguinte código:

```
public void Dispose()
{
    if (!ConfiguracaoCertificado.ManterDadosEmCache && _certificado != null)
    {
        _certificado.Reset();
        _certificado = null;
    }
}

~MDFeConfiguracao()
{
    if (!ConfiguracaoCertificado.ManterDadosEmCache && _certificado != null)
    {
        _certificado.Reset();
        _certificado = null;
    }
}
```

Note que o destrutor faz a mesma coisa do Dispose, assim, visando remover a duplicação de código, poderia analisar a possibilidade de encapsular a lógica de liberação de recursos em um método, onde, tanto o dispose, como o destrutor chame este método.

Sugestão (Pode ajustar conforme achar necessário): 
```
public void Dispose()
{
    LiberarRecursos();
}

~MDFeConfiguracao()
{
    LiberarRecursos();
}

private void LiberarRecursos()
{
    if (NaoDeveManterDadosDoCertificadoEmCache())
    {
        _certificado.Reset();
        _certificado = null;
    }
}

private bool NaoDeveManterDadosDoCertificadoEmCache()
    => !ConfiguracaoCertificado.ManterDadosEmCache && _certificado != null;
```

2024-06-18 15:02 UTC, AgnaldoSilva0 commented on DFe.Utils/ChaveFiscal.cs
>              chave.Append(((int)ufEmitente).ToString("D2"))
Aproveite que fez alterações nesse método, e alinhe os `Append`.

```
chave.Append(((int)ufEmitente).ToString("D2"))
     .Append(dataEmissao.ToString("yyMM"))
     .Append(cnpjEmitente)
     .Append(((int)modelo).ToString("D2"))
     .Append(serie.ToString("D3"))
     .Append(numero.ToString("D9"))
     .Append(tipoEmissao.ToString())
     .Append(cNf.ToString("D8"));
```

2024-06-18 15:07 UTC, AgnaldoSilva0 commented on MDFe.Classes/Extensoes/ExtMDFe.cs
Remover linha desnecessária. (73 ou 74)

2024-06-18 17:23 UTC, AgnaldoSilva0 commented on MDFe.Classes/Extensoes/ExtMDFeRetConsSitMDFe.cs
>              var arquivoSalvar = Path.Combine(caminhoXml,  chave + "-sit.xml");
Remover espaço a mais entre a virgula e o parametro `chave`.

`var arquivoSalvar = Path.Combine(caminhoXml, chave + "-sit.xml");`

2024-06-18 18:00 UTC, AgnaldoSilva0 commented on MDFe.Classes/Flags/MDFeTpCarga.cs
> +        Indefinido = 0,
A tag `tpCarga` é obrigatória.
A inserção do tipo Indefinido 0 é por algum motivo especifico? Já que não se encontra na lista de possíveis valores válidos para a tag.

2024-06-18 18:04 UTC, AgnaldoSilva0 commented on MDFe.Classes/Flags/MDFeTpComp.cs
Aproveite que fez alteração nesse enumerador, e corrija o nome: 
`DespesasBancariasEmiosDePagamentoOutras`
Para: 
`DespesasBancariasEMeiosDePagamentoOutras`

2024-06-18 18:20 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeDisp.cs
>          public decimal vValePed
Para seguir o padrão de nomenclaturas, poderia ajustar o `vValePed ` para `VValePed`.

2024-06-18 18:28 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeIde.cs
> +        public string ProxyDhIniViagem {
Mover a abertura de chave do método para a linha de baixo.

2024-06-18 18:32 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeIde.cs
> +
Remover linha desnecessária. (Linha 252)

2024-06-18 18:44 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfLocalCarrega.cs
> +                    return _latitude.ToString();
Remover o recuo do `return _latitude.ToString();`. Da maneira como está, dá a impressão que está dentro do if, o que não é verdade.

Sugestão: 
```
if (_latitude == null) return null;

return _latitude.ToString();
```

2024-06-18 18:46 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfLocalCarrega.cs
> +        [XmlElement("Longitude")]
A tag `longitude ` no xml é com letras minúsculas.

Ajustar para:
`[XmlElement("longitude")]`

2024-06-18 18:48 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfLocalDescarrega.cs
> +        [XmlElement("Longitude")]
Mesmo caso anterior.

Ajustar para:
`[XmlElement("longitude")]`

2024-06-18 18:50 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfLocalDescarrega.cs
> +        /// carregado o MDF-e.
O comentário tem um pequeno erro, essa tag se refere ao local de descarregamento, mas no comentário se refere ao carregamento.

Ajustar para:
```
/// 1 - Longitude do ponto geográfico onde foi
/// descarregado o MDF-e.
```

2024-06-18 18:51 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfLocalDescarrega.cs
> +        /// carregado o MDF-e.
O comentário tem um pequeno erro, essa tag se refere ao local de descarregamento, mas no comentário se refere ao carregamento.

Ajustar para:
```
/// 1- Latitude do ponto geográfico onde foi
/// descarregado o MDF-e.
```

2024-06-18 18:52 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfLocalDescarrega.cs
> +        /// 1 - Cep onde foi carregado o MDF-e.
O comentário tem um pequeno erro, essa tag se refere ao local de descarregamento, mas no comentário se refere ao carregamento.

Ajustar para:
`/// 1 - Cep onde foi descarregado o MDF-e.`

2024-06-18 19:01 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfMDFe.cs
>          }
Adicionar um espaço entre o final da chave do construtor e `/// <summary>`.
Mais especificamente entre as linhas 52 e 53.

2024-06-18 19:09 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfPag.cs
> +        /// 3 - Componentes do Pagamento do Frete.
Comentário não condiz com a tag, esse comentário é referente a tag Comp.

Ajustar para:
```
/// 3 - Identificador do responsável pelo pgto 
/// em caso de ser estrangeiro
```

2024-06-18 19:13 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfPag.cs
> +        /// 3 - Informações Bancárias.
Comentário não condiz com a tag, essa descrição é referente a tag InfBanc.

Ajustar para:
```
/// 3 - Indicador de operação de transporte de 
/// alto desempenho 
```

2024-06-18 19:17 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeInfPercurso.cs
>          public string ProxyUFPer {
Mover a abertura de chave do ProxyUFPer para a linha de baixo.

```
public string ProxyUFPer
{
    get { return UFPer.GetSiglaUfString(); }
    set { UFPer = UFPer.SiglaParaEstado(value); }
}
```

2024-06-18 19:45 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeProdPred.cs
> +/* ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA. Consulte a Licença Pública Geral Menor*/
Remover linha repetida.

2024-06-19 17:15 UTC, AgnaldoSilva0 commented on MDFe.Classes/Informacoes/MDFeVeicTracao.cs
> +                    UF = new Estado().SiglaParaEstado(value);
Na classe `MDFeVeicReboque` a propriedade `ProxyUF` existe o tratamento `else` setando null para UF em caso do valor informado ser vazio, mas aqui esse comportamento não foi usado. Tem algum motivo especifico?

2024-06-21 22:47 UTC, andrebts commented on MDFe.Classes/Flags/MDFeTpCarga.cs
> +        Indefinido = 0,
Não havia prestado atenção nele, o removi pois não há documentação que pude encontrar para embasar sua presença

2024-06-21 23:02 UTC, andrebts commented on MDFe.Classes/Informacoes/MDFeVeicTracao.cs
> +                    UF = new Estado().SiglaParaEstado(value);
Adicionei o tratamento também para MDFeVeicTracao.

2024-06-25 13:37 UTC, merged