Criação do campo indDeduzDeson na classe ICMSGeral
ZeusAutomacao/DFe.NET pull request #1550
Opened 2024-08-08 12:31 UTC by adrianotrentim

Criação do campo indDeduzDeson na classe ICMSGeral

2024-09-20 17:24 UTC, AgnaldoSilva0 requested changes

2024-09-20 17:24 UTC, AgnaldoSilva0 commented on NFe.Utils/Tributacao/Estadual/ICMSGeral.cs
> +        ///     Indicador do valor de desoneracao é deduzido do total da NF-e
Sugiro alterar o summary para o que explica diretamente o campo. Como a descrição indicada na sefaz:

![image](https://github.com/user-attachments/assets/97c7a6e5-ea84-435f-a956-115cda22600e)

2024-10-29 19:34 UTC, Valmir-Cunha commented
Olá,
Em razão da ausência de retorno, informamos que a modificação será integrada a partir do Pull Request #1562, e este PR será encerrado. Agradecemos a contribuição.

2024-10-29 19:34 UTC, closed without merging

2024-10-30 12:11 UTC, adrianotrentim commented
Ué, foi encerrado e vai ficar com o bug? não entendi....

2024-10-30 12:32 UTC, Valmir-Cunha commented
Olá, @adrianotrentim. O campo solicitado será adicionado. Ele foi adicionado e será integrado à branch master do projeto por meio do pull request de atualização da biblioteca em relação ao fork Hércules. O link para o arquivo com a inclusão do campo pode ser encontrado [aqui](https://github.com/ZeusAutomacao/DFe.NET/pull/1562/files#diff-6c413a195845819d2fac40eacfcdbdf2ff700ed6905bec744207c2bd03d16e13). O PR está em revisão no momento. 

Referente ao ajuste para debug, ele será feito em outro PR após a integração.

2024-10-30 12:38 UTC, adrianotrentim commented
Ah, sim, perfeito então, é que aqui apareceu que o PR foi fechado por falta de iteração, e a iteração que houve foi para modificar o summary, que eu realmente comi bronha e não vi a tempo. Mas rejeitar um PR por causa de comentários achei estranho. Mas blz então.