Solucao para problema no path
ZeusAutomacao/DFe.NET pull request #638
Opened 2018-01-29 19:15 UTC by pino

#637

2018-03-28 10:49 UTC, marcosgerene requested changes

2018-03-28 10:49 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> -            _path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
Esta variável "_path" não é utilizada em nenhum lugar além do método "SalvarArquivoXml"?

Se for: então está errado, mude para ```_path = Path.GetDirectoryName(AppDomain.CurrentDomain.BaseDirectory); ```
Se não for: remova a variável desnecessária

2018-03-29 11:39 UTC, robertorp commented
No AppTeste eu marquei a opção de salvar arquivo xml

Mandei uma consulta "Status do Serviço"

oque aconteceu foi o seguinte 

![salvar xml](https://user-images.githubusercontent.com/10251705/38086673-9f0102a6-332b-11e8-8f2e-abdf6fd35326.png)

veja que não mostrou o diretório onde sera salvo o xml, poderia modificar o appteste para aparecer o diretorio onde sera salvo que no caso e a raiz do projeto,
Talvez melhor dizendo existe a possibilidade de termos o diretório diretamente por default na classe ConfiguracaoServico.DiretorioSalvarXml (Por default vc usa o código Path.GetDirectoryName(AppDomain.CurrentDomain.BaseDirectory) ) assim eliminamos essa linha de código 
Linha eliminada
```
var dir = string.IsNullOrEmpty(_cFgServico.DiretorioSalvarXml)
                ? Path.GetDirectoryName(AppDomain.CurrentDomain.BaseDirectory)
                : _cFgServico.DiretorioSalvarXml;
```


por somente 
Novo Método SalvarArquivoXml
```
if (!_cFgServico.SalvarXmlServicos) return;
            
            if (string.IsNullOrEmpty(_cFgServico.DiretorioSalvarXml))
                throw new ArgumentException("Diretório inválido para salvar xmls");

            var stw = new StreamWriter(_cFgServico.DiretorioSalvarXml + @"\" + nomeArquivo);
            stw.WriteLine(xmlString);
            stw.Close();
```

Imagino eu que ficaria  melhor. Bom e somente uma opinião.

2018-03-29 11:41 UTC, marcosgerene reviewed
Aqui já não sei se é um erro ou não, mas "Path.GetDirectoryName" pega o nome do dietório e não o caminho, logo usar "AppDomain.CurrentDomain.BaseDirectory" sem o Path.GetDirectoryName acredito fazer mais sentido, mas ai já não tenho certeza...


E já que alterou, na linha de baixo está horrível (sei que não foi você que mexeu), mas aproveita o pull e já muda de 
```
var stw = new StreamWriter(dir + @"\" + nomeArquivo);
```

para 

```
var stw = new StreamWriter(Path.Combine(dir, nomeArquivo);
```

2018-03-29 11:42 UTC, marcosgerene requested changes
Aqui já não sei se é um erro ou não, mas "Path.GetDirectoryName" pega o nome do dietório e não o caminho, logo usar "AppDomain.CurrentDomain.BaseDirectory" sem o Path.GetDirectoryName acredito fazer mais sentido, mas ai já não tenho certeza...


E já que alterou, na linha de baixo está horrível (sei que não foi você que mexeu), mas aproveita o pull e já muda de 
```
var stw = new StreamWriter(dir + @"\" + nomeArquivo);
```

para 

```
var stw = new StreamWriter(Path.Combine(dir, nomeArquivo));
```

2018-03-29 11:54 UTC, pino commented
@robertorp Acho uma boa idéia colocar o AppDomain.CurrentDomain.BaseDirectory como default no ConfiguracaoServico.DiretorioSalvarXml. Vou implementar a sugestão

@marcosgerene ajustarei

2018-08-09 14:30 UTC, closed without merging