Ajustes na conversão de xml para classe, NFCe v4
ZeusAutomacao/DFe.NET pull request #677
Opened 2018-03-19 19:47 UTC by ebitencourt

Na forma anterior, urlChave sempre estava null pois a classe esta sendo gerada pelo xml

2018-03-19 20:58 UTC, robertorp commented
Estava dando algum erro a versão anterior? 
Ou somente uma maneira melhor que você implementou?

2018-03-19 21:23 UTC, ebitencourt commented
da forma anterior, o atributo urlChave nunca era preenchido
mantive com try/catch pois a versao 3.1 não possui urlChave

2018-03-19 21:34 UTC, marcosgerene commented
Me corrija se eu estiver errado, mas sempre que for  3,1 cairia no catch? O correto então não seria verificar se a versão é a 4.0 antes para evitar cair no catch e dar aquela "engasgadinha" que da quando o bloco try da erro?

2018-03-19 21:40 UTC, ebitencourt commented
Seria interessante, na verdade não encontrei outra forma de fazer.. Agradeço se puder fazer com a verificação de versão

2018-03-19 22:14 UTC, marcosgerene requested changes
Comentei no código uma solução. Testei aqui e aparentemente deu certo, mas não uso XmlReader nos meus projetos pessoais, teste com calma e aplique a correção.

2018-03-19 22:14 UTC, marcosgerene commented on NFe.Classes/infNFeSupl.cs
> +            //Caso a versao nao seja 4.0, nao existirá urlChave
Remova o try.. catch e adicione
```
if (reader.IsStartElement("urlchave"))
{
               reader.ReadStartElement("urlChave");
                 urlChave = reader.ReadString();
                 reader.ReadEndElement();
}
```
e teste novamente.

2018-03-19 23:12 UTC, ebitencourt commented
Valeu, funcionou perfeitamente.. assim vou conhecendo os recursos da linguagem

2018-03-20 12:53 UTC, marcosgerene requested changes
Faça um teste nas duas versões antes de sincronizar o seus commits no pull

2018-03-20 12:53 UTC, marcosgerene commented on NFe.Danfe.Nativo/NFCe/DanfeNativoNfce.cs
> +                foreach (var detPag in pag.detPag) {
O detPag não estará null no caso do V3.1? não seria interessante fazer 
```
if (pag.detPag !=null)
{
    ... foreach ...
}
```

2018-03-20 13:33 UTC, ebitencourt commented on NFe.Danfe.Nativo/NFCe/DanfeNativoNfce.cs
> +                foreach (var detPag in pag.detPag) {
bem observado, não havia testado na emissão somente na importação de xml onde ele não chega null

2018-03-29 11:47 UTC, marcosgerene requested changes
De resto não encontrei mais problemas

2018-03-29 11:47 UTC, marcosgerene commented on NFe.Danfe.Nativo/NFCe/DanfeNativoNfce.cs
> +namespace NFe.Danfe.Nativo.NFCe {
Por favor, desfaça essas mudanças na posição do **{**

2018-03-29 14:31 UTC, marcosgerene approved these changes

2018-03-29 14:33 UTC, merged