ALTERACAO DO TAMANHO DO CAMPO IDLOTE CONFORME MANUAL DO CONTRIBUINTE
ZeusAutomacao/DFe.NET pull request #681
Opened 2018-03-27 15:34 UTC by hbdbim

AJUSTE NO METODO ClasseParaXmlString PARA GARANTIR QUE A STRING ESTEJA EM UTF8, ALGUNS ESTADOS VALIDAM ESTA FORMATAÇÃO.

PEQUENO AJUSTE NA LEITURA DO XML DA NOTA QUANDO V4.00 ESTAVA DANDO ERRO [infNFeSupl.ReadXml].

ATUALIZAÇÃO DOS ENDEREÇOS DE WEBSERVICE DO MATO GROSSO.

QUANDO SE TENTA EMITIR UMA NOTA JÁ EMITIDA O RETORNO DO WEBSERVICE VEM [retConsReciNFe], DO ESPERADO [retEnviNFe], STRING REPLACE NO RETORNO PARA EVITAR EXCEÇÃO.

ADICIONADO DELEGATE ValidaCertificado PARA PODER TRATAR O RETORNO DA VALIDAÇÃO DO CERTIFICADO, DECORRENTE DE ALGUM BUG/INCONSISTENCIA RODANDO NO IIS NAO CONSEGUI IDENTIFICAR A CAUSA DO ERRO.

2018-03-27 21:48 UTC, marcosgerene requested changes
1. A mudança do idLote de int para double acredito que seja equivocada, e a melhor alternativa seja long.

2. A alteração proposta no "urlChave" para nfe 4.0 foi melhor tratada no pull #677.

3. Ainda estou em dúvida sobre ClasseParaXmlString, eu acredito que a melhor opção seja criar uma nova função "ClasseParaXmlStringUTF8" ou pelo menos criar um parâmetro para isso.

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Autorizacao/enviNFe3.cs
> +        public enviNFe3(string versao, double idLote, IndicadorSincronizacao indSinc, List<NFe> nFe)
Acredito que a melhor abordagem aqui seria usar long e não double, salvo engano, o idLote não permite ponto flutuante.

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Autorizacao/enviNFe3.cs
> +        public double idLote { get; set; }
Mesma revisão anterior, acredito que aqui o corretos seria usar long...

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Autorizacao/enviNFe4.cs
> +        public enviNFe4(string versao, double idLote, IndicadorSincronizacao indSinc, List<NFe> nFe)
double => Long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Autorizacao/enviNFe4.cs
> +        public double idLote { get; set; }
double => Long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Evento/envEvento.cs
> +        public double idLote { get; set; }
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Evento/retEnvEvento.cs
> +        public double idLote { get; set; }
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Recepcao/enviNFe2.cs
> +        public enviNFe2(string versao, double idLote, List<NFe> nFe)
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Recepcao/enviNFe2.cs
> +        public double idLote { get; set; }
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/Servicos/Recepcao/retEnviNFe.cs
> +        public double nRec { get; set; }
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        private RetornoRecepcaoEvento RecepcaoEvento(double idLote, List<evento> eventos, ServicoNFe servicoEvento)
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        public RetornoRecepcaoEvento RecepcaoEventoCancelamento(double idLote, int sequenciaEvento,
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        public RetornoRecepcaoEvento RecepcaoEventoCartaCorrecao(double idLote, int sequenciaEvento, string chaveNFe,
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        public RetornoRecepcaoEvento RecepcaoEventoManifestacaoDestinatario(double idLote, int sequenciaEvento,
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        public RetornoRecepcaoEvento RecepcaoEventoManifestacaoDestinatario(double idLote, int sequenciaEvento,
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        public RetornoNfeRecepcao NfeRecepcao(double idLote, List<Classes.NFe> nFes)
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        public RetornoNFeAutorizacao NFeAutorizacao(double idLote, IndicadorSincronizacao indSinc, List<Classes.NFe> nFes,
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        private RetornoNFeAutorizacao NFeAutorizacao4(double idLote, IndicadorSincronizacao indSinc, List<Classes.NFe> nFes, bool compactarMensagem)
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +            var retEnvio = new retEnviNFe().CarregarDeXmlString(retornoXmlString.Replace("retConsReciNFe", "retEnviNFe"));
Rapaz, acho que essa não é a melhor abordagem, me parece uma gambiarra, pois podem haver diferenças no layout dos schemas....

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +        private RetornoNFeAutorizacao NFeAutorizacaoVersao310(double idLote, IndicadorSincronizacao indSinc, List<Classes.NFe> nFes, bool compactarMensagem)
double => long

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +            var retEnvio = new retEnviNFe().CarregarDeXmlString(retornoXmlString.Replace("retConsReciNFe", "retEnviNFe"));
Acredito que não seja a melhor abordagem

2018-03-27 21:48 UTC, marcosgerene commented on NFe.Classes/infNFeSupl.cs
> +            if (reader.Name == "urlChave" || urlChave != null)
A proposta que revisei no pull #667 faz da seguinte forma:

```
if (reader.IsStartElement("urlChave")) {
    ...
}]
```

2018-03-27 21:48 UTC, marcosgerene commented on DFe.Utils/FuncoesXml.cs
> +            var result = XElement.Parse(xml.ToString()).ToString(SaveOptions.DisableFormatting);
Acredito que este tratamento deve ser feito na sua aplicação, ou se feito no  componente criar um novo método "ClasseParaXmlStringUTF8".

2018-03-28 00:34 UTC, hbdbim commented on DFe.Utils/FuncoesXml.cs
> +            var result = XElement.Parse(xml.ToString()).ToString(SaveOptions.DisableFormatting);
Não tem como tratar na aplicação de forma generica, teria que tratar campo a campo ou serializar e depois desserializar a classe.
Outro metodo tipo "ClasseParaXmlStringUTF8" seria bom mas esse metodo é invocado em diversos pontos da biblioteca.
Parametro talvez? Tem estado que valida outros que não validam.

2018-03-28 01:05 UTC, hbdbim commented on NFe.Servicos/ServicosNFe.cs
> +            var retEnvio = new retEnviNFe().CarregarDeXmlString(retornoXmlString.Replace("retConsReciNFe", "retEnviNFe"));
Confeco que nao parei para avaliar se a estrutura retornada confere com o tipo retConsReciNFe ou esta apenas errado o retorno do sefaz mesmo. Vou verificar o retorno exato. pq pra mim nao faz sentido, nao conheco linguagem de programação OO que pode retorna no mesmo metodo a classe A ou a classe B, um metodo um tipo de retorno.

2018-03-28 01:28 UTC, hbdbim commented
@marcosgerene Quanto ao idLote agora me veio uma questao, a definicao do manual do contribuiente diz tipo N Tam. 1-15, 
1 - o long é bem maior que isso.
2 - poderia ser preenchido com 00100000000001 ?
3 - os demais campos com o mesmo tipo N seguem o mesmo padrao ?

2018-03-28 10:17 UTC, marcosgerene commented
@hbdbim 
>@marcosgerene Quanto ao idLote agora me veio uma questao, a definicao do manual do >contribuiente diz tipo N Tam. 1-15,
>1 - o long é bem maior que isso.
>2 - poderia ser preenchido com 00100000000001 ?
>3 - os demais campos com o mesmo tipo N seguem o mesmo padrao ?

Tratar números inteiros grande usa-se long, double permite casas decimais e o idLote, salvo engano, não permite casas decimais.

>1 - o long é bem maior que isso.
Qual o problema em ser maior? o problema seria ser menor (caso do int (ou int32, como preferir)), o long (int64) é capaz de armazenar este valor.

>2 - poderia ser preenchido com 00100000000001 ?
Não entendi o sentido desse 00 antes do número "em si", números, não importa o tipo (decimal, double, int, long, smallint, float..) vão igorar os zeros à esquerda, do primeiro 1 pra frente sim cabe no long.

2018-04-05 11:37 UTC, marcosgerene commented on NFe.Classes/Servicos/Recepcao/retEnviNFe.cs
> +        public double nRec { get; set; }
Aqui ainda não foi alterado para long

2018-04-05 11:37 UTC, marcosgerene commented on NFe.Classes/infNFeSupl.cs
> +            if (reader.Name == "urlChave" || urlChave != null)
O pull #667 foi aceito, desfaça esta alteração

2018-04-05 11:39 UTC, marcosgerene commented on NFe.Servicos/ServicosNFe.cs
> +            var retEnvio = new retEnviNFe().CarregarDeXmlString(retornoXmlString.Replace("retConsReciNFe", "retEnviNFe"));
Isto está errado, da forma que está feita é bem provável que teremos um bug no futuro

2018-04-05 13:00 UTC, rodrigordi commented
Bom dia essoal,

pq voces não usam como string mesmo ?

Eu ainda não entendi se é no idLote do envio ou se é no nRec do retorno do processamento. 

XSD dos tipos:

<xs:simpleType name="TIdLote">
		<xs:annotation>
			<xs:documentation> Tipo Identificação de Lote</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="[0-9]{1,15}"/>
		</xs:restriction>
	</xs:simpleType>


<xs:simpleType name="TRec">
		<xs:annotation>
			<xs:documentation>Tipo Número do Recibo do envio de lote de NF-e</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="[0-9]{15}"/>
		</xs:restriction>
	</xs:simpleType>

2018-04-05 14:25 UTC, marcosgerene commented
@rodrigordi 

```
Bom dia essoal,

pq voces não usam como string mesmo ?

Eu ainda não entendi se é no idLote do envio ou se é no nRec do retorno do processamento.

XSD dos tipos:

<xs:simpleType name="TIdLote">
xs:annotation
xs:documentation Tipo Identificação de Lote</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:whiteSpace value="preserve"/>
<xs:pattern value="[0-9]{1,15}"/>
</xs:restriction>
</xs:simpleType>

<xs:simpleType name="TRec">
xs:annotation
xs:documentationTipo Número do Recibo do envio de lote de NF-e</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:whiteSpace value="preserve"/>
<xs:pattern value="[0-9]{15}"/>
</xs:restriction>
</xs:simpleType>
```

Olhe o pattern [0-9]{1,15}, so aceita numerais, usar string vai permitir letras e usar letras quebra o pattern do xsd, algo que pode ser facilmente evitado somente "tipando" o campo da forma correta.

2018-04-05 15:36 UTC, rodrigordi commented
Ah sim. isso é verdade. 

int32.Max = 2147483647 (10 casas)
uint32.Max = 4294967295 (10 casas)
int64.Max = 9223372036854775807 (19 casas)
uint64.Max = 18446744073709551615 (20 casas)

2018-04-05 15:38 UTC, rftd commented
uInt seria mais certo ai pois no caso o patern não aceita números negativos.

2018-08-09 14:31 UTC, closed without merging