Adicionado detPag e vTroco para v4.0, mantida compatibilidade com v3.1
ZeusAutomacao/DFe.NET pull request #683
Opened 2018-04-03 17:06 UTC by ebitencourt

2018-04-03 17:36 UTC, robertorp commented
Isso e na impressão ne?

2018-04-03 17:59 UTC, ebitencourt commented
sim

2018-04-05 11:26 UTC, marcosgerene commented on NFe.Danfe.Fast/NFCe/NFCe.frx
> +<Report ScriptLanguage="CSharp" ReferencedAssemblies="System.dll&#13;&#10;System.Drawing.dll&#13;&#10;System.Windows.Forms.dll&#13;&#10;System.Data.dll&#13;&#10;System.Xml.dll&#13;&#10;NFe.Classes.dl
Mudou  a versão do Fast para 2018 e não mudou as dlls anexadas, por isso que falo que tem que remover as dlls de vez ou (melhor opção) separar os projetos de impressão.

2018-04-05 11:34 UTC, marcosgerene requested changes

2018-04-05 11:34 UTC, marcosgerene commented on NFe.Danfe.Fast/NFCe/NFCe.frx
> +    <BusinessObjectDataSource Name="NFCe" ReferenceName="NFCe" DataType="null" Enabled="true">
O DataType foi alterado daqui pra baixo em todos os lugares do tipo "correto" para null, acredito que voce abriu o design sem ser pelo demo, ou sem carregar uma nota nos DataSources, isso vai quebrar todo o arquivo.

2018-04-05 11:34 UTC, marcosgerene commented on NFe.Danfe.Fast/NFCe/NFCe.frx
> -          <Column Name="KeyInfo" DataType="DFe.Classes.Assinatura.KeyInfo, DFe.Classes, Version=0.0.0.6, Culture=neutral, PublicKeyToken=null">
Vou comentar somente aqui porque é muita alteração pelo mesmo motivo citado acima, repara que o DataType de tudo deixou de ser o correto e passou a ser null, por favor corrija.

PS: Acredito que seja mais fácil fazer um "undo" nesse arquivo, e só refazer as alterações que você realmente gostaria de fazer.

2018-04-05 11:34 UTC, marcosgerene commented on NFe.Danfe.Fast/NFCe/NFCeQRReduzido.frx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Anexe um print do resultado desse frx na conversa do pull, por favor, acredito que algumas pessoas não entenderam do que se trata o pull e ter isso em mãos até desperte a curiosidade por usar essa nova opção.

2018-04-05 19:10 UTC, ebitencourt commented
Valeu pelas dicas, vou fazer denovo e já mando outro pull

2018-04-05 19:10 UTC, closed without merging