Forçando CNPJ de 14 digitos
ZeusAutomacao/DFe.NET pull request #701
Opened 2018-04-23 23:32 UTC by rubenlr

2018-04-24 12:07 UTC, marcosgerene requested changes
O campo "cnpjEmitente" é uma string, é só passar o cnpj correto, não faz sentido algum essa mudança.

Você está colocando no componente a responsabilidade de fazer um tratamento que deve ser feita pela aplicação, pelo que pude entender você deve ter alguma base de dados com o cnpj sem os zeros à esquerda, isso quem tem que corrigir é a aplicação, o componente não deve manipular dados, apenas serealizar eles.

2018-04-24 12:13 UTC, closed without merging

2018-05-22 22:21 UTC, rubenlr commented
Sim, foi o problema. Mas a falta de tratamento desse tipo de erro complicou bastante a integração com a biblioteca.
Acho que poderia ter pelo menos uma exception ou algo que indicasse qual é o erro.

2018-05-23 10:48 UTC, marcosgerene commented
> Sim, foi o problema. Mas a falta de tratamento desse tipo de erro complicou bastante a integração com a biblioteca.
> Acho que poderia ter pelo menos uma exception ou algo que indicasse qual é o erro.

Tratamento das informações é responsabilidade da aplicação, o campo em questão é uma string, basta informar corretamente.

2018-05-23 15:10 UTC, rubenlr commented
A biblioteca não deve fornecer mensagens de erro claras?

Eu não tenho nem como usar a dll porque estoura exceção sem nenhuma
mensagem de erro possível de interpretar. Preciso do código fonte, para
debugar a dll e entender o que foi que deu erro. Isso não me parece um
processo razoável.

Att,

Rúben Lício Reis
+55 11 967041245

2018-05-23 7:49 GMT-03:00 Marcos Gerene F. Spirito <notifications@github.com
>:

> Sim, foi o problema. Mas a falta de tratamento desse tipo de erro
> complicou bastante a integração com a biblioteca.
> Acho que poderia ter pelo menos uma exception ou algo que indicasse qual é
> o erro.
>
> Tratamento das informações é responsabilidade da aplicação, o campo em
> questão é uma string, basta informar corretamente.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ZeusAutomacao/DFe.NET/pull/701#issuecomment-391304369>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZ4bORj8CIaFM15rlbowXLoEweJjFDJks5t1T6dgaJpZM4Tgxpa>
> .
>

2018-05-23 15:56 UTC, marcosgerene commented
>A biblioteca não deve fornecer mensagens de erro claras?

Não. rs

Vamos lá, é exatamente este o ponto. A biblioteca deve somente oferecer para você uma camada entre o XSD (para gerar os xmls) e  suas próprias classes, além de se comunicar com o webservice.

Todo e qualquer tratamento é por via de regra responsabilidade do software emissor. O que você está dizendo é o mesmo que pedir que a biblioteca saiba que o valor do imposto é base x aliquota, isso pode parecer óbvio, mas não responsabilidade da biblioteca, ela tem que simplesmente que pegar o valor que você informou  e por no XML.

Agora se você falasse "olha, seria legal a gente ter uma camada de tratamento" eu diria "então crie um novo projeto que use este como base" e deixe à cargo do usuário usar ele ou não. E te explico: Quando você faz algum tratamento no que o usuário informou e o resultado final, qualquer falha que isto possa trazer, fora a responsabilidade, pode trazer prejuízos a outras pessoas, o projeto da NFe é cheio de regras de negócio que se aplicam a algumas empresas e a outras não.

>Eu não tenho nem como usar a dll porque estoura exceção sem nenhuma
mensagem de erro possível de interpretar. Preciso do código fonte, para
debugar a dll e entender o que foi que deu erro. Isso não me parece um
processo razoável.

Me desculpe, mas é só chamar o método validar e ver a excessão gerada pelos XSDs, acredito que não seja necessário um conhecimento mais aprofundado para interpretar o erro.

2018-05-23 23:59 UTC, robertorp commented
Já eu sugiro a criação de um repositório a parte que contenha o Zeus internamente para validar as informações. 
Posso estar estudando a possibilidade de criação do mesmo.

2018-05-24 13:30 UTC, marcosgerene commented
@robertorp 
>Já eu sugiro a criação de um repositório a parte que contenha o Zeus internamente para validar as informações.
Posso estar estudando a possibilidade de criação do mesmo.

Já sabe minha opinião:
>Agora se você falasse "olha, seria legal a gente ter uma camada de tratamento" eu diria "então crie um novo projeto que use este como base" e deixe à cargo do usuário usar ele ou não.

Acredito que a sua abordagem seja a melhor, resolve os dois problemas, cria uma camada a mais sem interferir no Core do projeto, parabéns!

2018-05-24 20:14 UTC, rubenlr commented
Entendi. Me parece que eu estou usando o caminho errado para debugar.

A questão talvez então seja um wiki com o caminho. Eu me disponho a ajudar
nisso, caso vocês achem interessante. Mas precisarei de ajuda,
possivelmente, pois não domino exatamente a biblioteca ainda.

Att,

Rúben Lício Reis
+55 11 967041245

2018-05-23 12:56 GMT-03:00 Marcos Gerene F. Spirito <
notifications@github.com>:

> A biblioteca não deve fornecer mensagens de erro claras?
>
> Não. rs
>
> Vamos lá, é exatamente este o ponto. A biblioteca deve somente oferecer
> para você uma camada entre o XSD (para gerar os xmls) e suas próprias
> classes, além de se comunicar com o webservice.
>
> Todo e qualquer tratamento é por via de regra responsabilidade do software
> emissor. O que você está dizendo é o mesmo que pedir que a biblioteca saiba
> que o valor do imposto é base x aliquota, isso pode parecer óbvio, mas não
> responsabilidade da biblioteca, ela tem que simplesmente que pegar o valor
> que você informou e por no XML.
>
> Agora se você falasse "olha, seria legal a gente ter uma camada de
> tratamento" eu diria "então crie um novo projeto que use este como base" e
> deixe à cargo do usuário usar ele ou não. E te explico: Quando você faz
> algum tratamento no que o usuário informou e o resultado final, qualquer
> falha que isto possa trazer, fora a responsabilidade, pode trazer prejuízos
> a outras pessoas, o projeto da NFe é cheio de regras de negócio que se
> aplicam a algumas empresas e a outras não.
>
> Eu não tenho nem como usar a dll porque estoura exceção sem nenhuma
> mensagem de erro possível de interpretar. Preciso do código fonte, para
> debugar a dll e entender o que foi que deu erro. Isso não me parece um
> processo razoável.
>
> Me desculpe, mas é só chamar o método validar e ver a excessão gerada
> pelos XSDs, acredito que não seja necessário um conhecimento mais
> aprofundado para interpretar o erro.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ZeusAutomacao/DFe.NET/pull/701#issuecomment-391400278>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZ4bKBLYV_Dt1_vSH9DD--Ms1Kec0Vvks5t1YaVgaJpZM4Tgxpa>
> .
>

2018-05-24 20:15 UTC, rubenlr commented
Uma camada de validação, pura e simples, a parte, parece bem interessante.
Não entendo exatamente o tamanho do trabalho para isso.

Att,

Rúben Lício Reis
+55 11 967041245

2018-05-23 20:59 GMT-03:00 Roberto Alves Pereira <notifications@github.com>:

> Já eu sugiro a criação de um repositório a parte que contenha o Zeus
> internamente para validar as informações.
> Posso estar estudando a possibilidade de criação do mesmo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ZeusAutomacao/DFe.NET/pull/701#issuecomment-391541006>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAZ4bDoR8ntoHkHV0k5gTdBQT_-ir999ks5t1ffogaJpZM4Tgxpa>
> .
>

2018-05-25 01:01 UTC, marcosgerene commented
> Entendi. Me parece que eu estou usando o caminho errado para debugar.
>
>A questão talvez então seja um wiki com o caminho. Eu me disponho a ajudar
>nisso, caso vocês achem interessante. Mas precisarei de ajuda,
>possivelmente, pois não domino exatamente a biblioteca ainda.

Não entendi o que você disse para ser sincero, MASSSS... sobre o wiki, realmente eu acho bem ruim o wiki do Dfe.Net, mas nunca tive tempo de fazer um melhor e mandar PR, então simplesmente ignoro ele, agora os outros contribuidores não sei o que acham. Hoje pelo tamanho do projeto acredito até mesmo que ele merecia uma página só para ele (como o npgsql tem), mas ai é devaneio, acredito que isso nunca vai ser feito sem um patrocínio, o pessoal que contribui geralmente foca em outros pontos (existe um PR do @robertorp aberto faz tempo que também sem um patrocínio tende a demorar)  a documentação do projeto realmente é ruim, impossível discordar, mas os contribuidores mais assíduos tem seus empregos e suas empresas, não vão(mos) focar nisso (pelo menos eu não).

>Uma camada de validação, pura e simples, a parte, parece bem interessante.
>Não entendo exatamente o tamanho do trabalho para isso.

Grande. Mas, sendo open source, se tiver grande adoção você não trabalha sozinho.

2018-05-25 13:23 UTC, marcosgerene commented
>Não entendi o que você disse para ser sincero, MASSSS... sobre o wiki, realmente eu acho bem ruim o wiki do Dfe.Net, mas nunca tive tempo de fazer um melhor e mandar PR, então simplesmente ignoro ele, agora os outros contribuidores não sei o que acham. Hoje pelo tamanho do projeto acredito até mesmo que ele merecia uma página só para ele (como o npgsql tem - http://www.npgsql.org), mas ai é devaneio, acredito que isso nunca vai ser feito sem um patrocínio, o pessoal que contribui geralmente foca em outros pontos (existe um PR do @robertorp aberto faz tempo que também sem um patrocínio tende a demorar) a documentação do projeto realmente é ruim, impossível discordar, mas os contribuidores mais assíduos tem seus empregos e suas empresas, não vão(mos) focar nisso (pelo menos eu não).

https://github.com/ZeusAutomacao/DFe.NET/commit/aa8b5ac9e35ab703e09c230f71fb3239decc66bc

Dei uma melhorada no wiki anterior, deixei ele menor e mais claro, além de atualizar para a nova realidade do projeto, mas confesso que ainda está longe do ideal.