Pequenos ajustes no projeto "NFe.Integracao"
ZeusAutomacao/DFe.NET pull request #734
Opened 2018-05-15 17:54 UTC by AndrewsFB

- Alguns bugs foram resolvidos.
- Adicionada a possibilidade de emitir NFC-e para MG.
- Foi criado um recurso para imprimir o NFC-e.

2018-05-15 22:05 UTC, marcosgerene commented
Por favor, resolva os conflitos, basicamente são versões do Assembly

2018-05-16 11:47 UTC, AndrewsFB commented
Feito.

2018-05-19 23:39 UTC, marcosgerene requested changes

2018-05-19 23:39 UTC, marcosgerene commented on NFe.Integracao/NFeFacade.cs
> +            ConfiguracaoServico.Instancia.VersaoRecepcaoEventoCceCancelamento = VersaoServico.ve400;
As duas versões ainda funcionam, seria interessante criar uma opção para definir qual usar...

2018-05-19 23:39 UTC, marcosgerene commented on NFe.Integracao/Program.cs
> +        /// <param name="dadosDaImpressao">Informações da impressão no formato: pathDoArquivoXml#localOndeSalvarOJpeg</param>
Aqui pelo que vi da assinautra do método é "pathDoArquivoXml#localOndeSalvarOJpeg#idToken#Csc"

2018-05-21 12:38 UTC, AndrewsFB commented
Feito.

2018-05-21 12:41 UTC, marcosgerene approved these changes

2018-05-21 12:42 UTC, marcosgerene commented
Pra mim está ok, não vou aceitar o pull porque não uso o NFe.Integracao, fica dificil eu analisar mais à fundo, vou aguardar o @robertorp  ou o @adeniltonbs aceitar ou dar um ok, mas ao meu ver está tudo ok.

2018-05-21 12:44 UTC, AndrewsFB commented
Tranquilo Marcos. 
Confesso que estranhei bastante a integração, está bem diferente de quando eu construí. Tem até um conceito que foi mudado que fez muita diferença pro meu uso aqui. Depois vou abrir uma issue pra falarmos sobre o assunto...

2018-05-28 20:30 UTC, robertorp commented
Resolva o conflito para estar aceitando o pull

2018-05-29 12:49 UTC, AndrewsFB commented
Quais conflitos?

2018-05-29 12:56 UTC, robertorp commented
no final desse pull olhe a mensagem 

This branch has conflicts that must be resolved

NFe.Integracao/NFeFacade.cs

2018-06-01 12:37 UTC, AndrewsFB commented
Feito.

2018-06-01 14:25 UTC, robertorp commented on NFe.Integracao/NFeFacade.cs
> +            ConfiguracaoServico.Instancia.VersaoNfceAministracaoCSC = versaoNFe;
Vou aprovar o pull mas aqui deixo somente uma observação
Agora você pode optar pelo uso de 

`ConfiguracaoServico.Instancia.VersaoLayout = 4.00 ou 3.00` e o próprio zeus se encarrega de selecionar as versões corretas dos serviços

2018-06-01 14:29 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.NfeInutilizacao, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sefaz.ms.gov.
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 14:31 UTC, robertorp commented
Somente mesmo a questão das urls de MT que precisam ser corrigidas na minha visão, para ficar zerado

2018-06-01 17:36 UTC, AndrewsFB commented
Corrigido.

2018-06-01 17:41 UTC, robertorp approved these changes

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.NfeConsultaProtocolo, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sefaz.ms
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.NfeStatusServico, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sefaz.ms.gov
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.NfeConsultaCadastro, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sefaz.ms.
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEventoCancelmento, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sef
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.RecepcaoEventoCartaCorrecao, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.s
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.NFeAutorizacao, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sefaz.ms.gov.b
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:41 UTC, robertorp commented on NFe.Servicos/Enderecador.cs
> +                endServico.Add(new EnderecoServico(ServicoNFe.NFeRetAutorizacao, VersaoServico.ve400, TipoAmbiente.taHomologacao, emissao, Estado.MT, ModeloDocumento.NFe, "https://hom.nfe.sefaz.ms.go
url errada a correta e a anterior
Observe que as urls anteriores estão para MT
já as novas urls aqui estão para MS

2018-06-01 17:42 UTC, robertorp commented
obrigado @AndrewsFB  !

2018-06-01 17:42 UTC, merged