Acerto de acentuação para Sefaz MT - issue 893
ZeusAutomacao/DFe.NET pull request #921
Opened 2018-11-28 15:47 UTC by ocult

Erro ocorria ao enviar a carta de correção (em ambiente de Produção) com acentuação para a Sefaz MT.

Correção conforme issue:
https://github.com/ZeusAutomacao/DFe.NET/issues/893#event-1992073252

2018-11-28 16:28 UTC, marcosgerene requested changes
A sua função não remove caracteres especiais, somente letras com acentos e já existe uma função para isso no projeto.

E forçar isso na classe ServicosNFe que traria alterações para todos os estados não me parece a melhor solução.  Neste caso acredito que você deveria fazer o tratamento antes de informar o texto.

2018-11-29 11:45 UTC, ocult commented
Respondendo, a minha função não remove caracteres especiais, somente letras com acentos, mas não encontrei uma similar no projeto para ser usado ali, por isso a criei no sharedutils.

E quanto forçar isso na classe ServicosNFe que traria alterações para todos os estados, fiz no mesmo ponto em que já há uma tratativa para estado do MT (único até o momento que percebi problema). Por isso que acredito que fazer o tratamento antes de informar o texto não seria tão vantajoso, uma vez que o a tratativa do estado de MT (desvio de fluxo) já existe e utilizei o mesmo.

Agora é com vocês acreditarem no que é melhor pro projeto...

:)

2018-11-29 18:06 UTC, marcosgerene commented
@ocult 

>Respondendo, a minha função não remove caracteres especiais, somente letras com acentos, mas não encontrei uma similar no projeto para ser usado ali, por isso a criei no sharedutils.

https://github.com/ZeusAutomacao/DFe.NET/blob/069db19c027981b9ac5cc70e14ef912bbdf7cae7/Shared.DFe.Utils/StringExtencoes.cs

>E quanto forçar isso na classe ServicosNFe que traria alterações para todos os estados, fiz no mesmo ponto em que já há uma tratativa para estado do MT (único até o momento que percebi problema). Por isso que acredito que fazer o tratamento antes de informar o texto não seria tão vantajoso, uma vez que o a tratativa do estado de MT (desvio de fluxo) já existe e utilizei o mesmo.

Pode me mandar aonde isso acontece? Te confesso que desconheço a causa.
Lembro de alguns tratamentos específicos para alguns estados em pontos aonde o usuário não pode intervir, mas neste caso o campo que você está mandando interferir é informado diretamente pelo usuário, por isso acho que a remoção de caracteres deveria vir do software.

Essa discussão já foi levantada aqui algumas vezes de até aonde a biblioteca deveria ir, este talvez seja o maior ponto de discordância entre eu e o @robertorp... Particularmente sou contra qualquer "manipulação" do que o desenvolvedor informou, salvo quando o desenvolvedor não tem como informar já corretamente.

>Agora é com vocês acreditarem no que é melhor pro projeto...

Eu não concordo com a alteração, não acho que está incorreta, não está. A questão aqui é "filosófica", acho que já explanei isso anteriormente, vamos aguardar uma avaliação do @robertorp  ou do @adeniltonbs  sobre o caso.


> :)

:)

2018-11-30 19:40 UTC, adeniltonbs commented
Boa tarde @ocult,
Desde já muito obrigado por sua colaboração.
Sua implementação já existe na biblioteca, e, recentemente foram feitos ajustes nelas. Por favor, dê uma olhada nos commits 75512d7a471b710027a6cb35251ffeddbb41dd0d e 756e7f6bc70b2551331b9d74d752fc674c655bb2 e teste pra ver se atende sua demanda.

2018-11-30 19:40 UTC, closed without merging