DAMDFE - correção para exibição correta dos vales pedágio
ZeusAutomacao/DFe.NET pull request #973
Opened 2019-05-07 19:12 UTC by fellipesales

Não exibia os vales pedágios no DAMDFE, alterado para pegar as informações da TAG ANTT.

![image](https://user-images.githubusercontent.com/6295777/57326446-e34e7380-70e2-11e9-8b80-167e539d670b.png)

2019-05-07 20:31 UTC, robertorp commented
Podia mandar uma foto por favor

2019-05-07 20:54 UTC, fellipesales commented
![image](https://user-images.githubusercontent.com/6295777/57332400-126be180-70f1-11e9-98ec-751f302c412d.png)

2019-05-08 21:27 UTC, marcosgerene commented
Os campos anteriores era da versão 1.00, acredito que seria interessante verificar a versão e preencher conforme a versão correta.

Da forma como estava quebra impressão de MDFe antigos  e da forma como estava não funcionava novos.

2019-05-08 21:29 UTC, marcosgerene requested changes
https://github.com/ZeusAutomacao/DFe.NET/pull/973#issuecomment-490657345

2019-05-08 22:04 UTC, fellipesales commented
Realmente, farei as validações.

2019-07-21 19:46 UTC, closed without merging